### ISSUE TITLE
#Bug PlacementBoxesRendering

### ISSUE THREAD

**Issue by KawaiiTamako** [eatmyvenom/litematica-printer#1]
Minecraft version : 1.15.2
Mod version : 1.15.0-0.0.0-dev.20200116
![20200830024027](https://user-images.githubusercontent.com/51044119/91644022-d8ca9280-ea27-11ea-8172-3bfd8c898b08.png)
![20200830024040](https://user-images.githubusercontent.com/51044119/91644024-db2cec80-ea27-11ea-8892-22212e61cfe3.png)

**Comment by KawaiiTamako** [comment]
@asiekierka @eatmyvenom

**Comment by KawaiiTamako** [comment]
@Andrews54757

**Comment by eatmyvenom** [comment]
Why would you ping everyone who is listed?

**Comment by eatmyvenom** [comment]
This is also for 1.15 which I don't support and it is because you need to update the mod and malilib

**Comment by KawaiiTamako** [comment]
?

**Comment by KawaiiTamako** [comment]
> 这也适用于1.15，我不支持，因为您需要更新mod和malilib

k
