### ISSUE TITLE
[WON'T FIX] Excessive ghost blocks on paper/spigot servers

### ISSUE THREAD

**Issue by salmornal** [eatmyvenom/litematica-printer#13]
Im trying to build a large glass dome atm and if I use this printer and then reconnect like half of the blocks didnt actually get placed. This left my dome 50 percent air and 50 percent glass. Anyone else experiencing this issue?

**Comment by sleepytyler** [comment]
Yes this is pretty common, I assume it is from server lag/possible anticheats but Im only just starting to get into minecraft dev work. I do not think this github is maintained anymore

**Comment by LimesKey** [comment]
The creator of the mod replied to me and told me that he/she spent hours trying to fix this bug and was unsuccessful. The bug only applies to Minecraft Paper servers only.

**Comment by eatmyvenom** [comment]
> The creator of the mod replied to me and told me that he/she spent hours trying to fix this bug and was unsuccessful. The bug only applies to Minecraft Paper servers only.

Yea so this isn't really something that can be helped without making excessive efforts to work around various parts of papers built-in anticheat. I do not have any plans to support paper either now or in the future. This mod is meant first and foremost for technical Minecraft servers running vanilla or fabric carpet servers. Anything else is too much for me to deal with.

**Comment by kyrielie** [comment]
It is partially fixed when I lowered the easyplacemoderange to 1. There were less blocks missing, I think.
