### ISSUE TITLE
Getting .jar file?

### ISSUE THREAD

**Issue by SatheTS** [eatmyvenom/litematica-printer#19]
From what I know, the code requires the I manually build it into a .jar file myself using gradle (or something similar), but I have no idea how after a few days of working at it. Can you link a tutorial or give a quick rundown on how to get the .jar file from the source code?
Thanks a bunch

**Comment by jensvh** [comment]
After downloading this repo, unpack the zip file. Open a terminal or cmd and move into the `litematica-printer-master` folder. Now type in `gradlew.bat build` this should generate a few jars in the folder `litematica-printer-master/build/libs`. Their you should see a few jar files, `litematica-printer-mc1.17.1-1.0.0.jar` is the one you need to put into your mods folder. Good luck!

**Comment by SatheTS** [comment]
Aha! My issue was not including .bat for the gradlew call. Thanks for the quick and comprehensive response, as well as keeping this mod up to date!

**Comment by SatheTS** [comment]
Aha! My issue was not including .bat for the gradlew call. Thanks for the quick and comprehensive response, as well as keeping this mod up to date!
