### ISSUE TITLE
misplace when move while placing

### ISSUE THREAD

**Issue by aria1th** [eatmyvenom/litematica-printer#2]
When I easyplace it and move over - or rotate, blocks are often misplaced with any interval (or placing rounds per cycle).

It happens in singleplayer / multiplayer, creative / survival.

Seems its placement behavior is relative postion.

*I'm using it instead of paste schematic in creative server - thanks for it anyway

**Comment by eatmyvenom** [comment]
I've tested this tons including while flying in creative. I am personally unable to reproduce this error.
