### ISSUE TITLE
how i can use litematica printer

### ISSUE THREAD

**Issue by iFsp3D** [eatmyvenom/litematica-printer#7]
can anyone help me to install the litematica printer please

**Comment by Impydude2000** [comment]
go to the "code" tab, under "Releases" press the release with the latest pin on it then do what it tells you to do

**Comment by DragonEggBedrockBreaking** [comment]
Would you mind closing this bug report? You just need to go to 'releases', download the .jar file and put it in your mods folder with litematica.

**Comment by Impydude2000** [comment]
> download the .jar file and put it in your mods folder with litematica.

Actually, I'm fairly sure you can't have litematica. and this mod in your "mods" folder at the same time.

**Comment by DragonEggBedrockBreaking** [comment]
> Actually, I'm fairly sure you can't have litematica. and this mod in your "mods" folder at the same time.

What are you talking about? This mod *requires litematica in the mods folder to work*. **It is literally in the code and the README**.

![image](https://user-images.githubusercontent.com/68545280/110202643-12120e00-7e62-11eb-9fe3-4d088199dbb0.png)

**Comment by Impydude2000** [comment]
> > Actually, I'm fairly sure you can't have litematica. and this mod in your "mods" folder at the same time.
> 
> What are you talking about? This mod _requires litematica in the mods folder to work_. **It is literally in the code and the README**.
> 
> ![image](https://user-images.githubusercontent.com/68545280/110202643-12120e00-7e62-11eb-9fe3-4d088199dbb0.png)

oh, I'm stupid, 1. most of the other mods like this require to not have litematica with the mod
2. I couldn't get it to work and I thought this was the problem.

**Comment by DragonEggBedrockBreaking** [comment]
> oh, I'm stupid, 1. most of the other mods like this require to not have litematica with the mod

In terms of mods that add more features to another mod, there are two variants. One is a fork, which is a copy of the mod, but with more features, therefore you only need the fork, and cannot have the original mod. There are also extensions, which require the original mod to be there, and only add features using either an API or Mixins.

**Comment by Impydude2000** [comment]
ok
